### ISSUE TITLE
[Close a room] A renommer en "quit"

### ISSUE THREAD

**Issue by D-Mith** [webcom-components/visio-sample#1]
Pas de possibilité de "clore" une room. La fonction "clore" permet juste de "quitter" la room. 
Est-ce possible de renommer le "close" par "quit" ?

**Comment by paulmusso** [comment]
Oui effectivement. Reach ne permet pas de fermer une room, seulement de la quitter. Du coup je supprime le bouton de cloture

**Comment by paulmusso** [comment]
Fixed
